# Generated by Django 4.0.6 on 2022-11-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal_app', '0002_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(max_length=2),
        ),
    ]
